"""
collect_github_releases.py — Pull GitHub release asset download counts.

Usage:
    python collect_github_releases.py

Output:
    data/github_releases.parquet   one row per asset — cumulative download count

Why this matters:
    GitHub Releases are the primary distribution channel for native
    installers and prebuilt binaries that don't ship via PyPI (TensorRT,
    OpenVINO Windows installers, Core ML tools, ExecuTorch mobile prebuilts).
    Download counts are cumulative since release date — snapshot only.
"""

from __future__ import annotations

import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests

DATA_DIR = Path(__file__).parent / "data"
DATA_DIR.mkdir(exist_ok=True)
OUT_PATH = DATA_DIR / "github_releases.parquet"

TOKEN = os.environ.get("GITHUB_TOKEN")
HEADERS: dict[str, str] = {
    "Accept": "application/vnd.github+json",
    "User-Agent": "qualcomm-mi-dashboard",
}
if TOKEN:
    HEADERS["Authorization"] = f"Bearer {TOKEN}"

REQUEST_DELAY = 2.0 if TOKEN else 6.5
MAX_RELEASES_PAGES = 5  # up to 500 releases per repo

# Repos whose releases are a meaningful distribution channel
# (i.e. users actually download installers/binaries from here,
# not just source tarballs auto-generated by GitHub)
REPOS: list[dict[str, str]] = [
    {"repo": "apple/coremltools",              "vendor": "Apple",     "affinity": "native"},
    {"repo": "ml-explore/mlx",                 "vendor": "Apple",     "affinity": "native"},
    {"repo": "openvinotoolkit/openvino",       "vendor": "Intel",     "affinity": "native"},
    {"repo": "intel/neural-compressor",        "vendor": "Intel",     "affinity": "native"},
    {"repo": "NVIDIA/TensorRT",                "vendor": "NVIDIA",    "affinity": "native"},
    {"repo": "NVIDIA/TensorRT-LLM",            "vendor": "NVIDIA",    "affinity": "native"},
    {"repo": "NVIDIA/cuda-python",             "vendor": "NVIDIA",    "affinity": "native"},
    {"repo": "microsoft/onnxruntime",          "vendor": "Microsoft", "affinity": "abstracted"},
    {"repo": "microsoft/olive",                "vendor": "Microsoft", "affinity": "abstracted"},
    {"repo": "microsoft/DirectML",             "vendor": "Microsoft", "affinity": "abstracted"},
    {"repo": "google-ai-edge/mediapipe",       "vendor": "Google",    "affinity": "abstracted"},
    {"repo": "google-ai-edge/LiteRT",          "vendor": "Google",    "affinity": "abstracted"},
    {"repo": "google-ai-edge/ai-edge-torch",   "vendor": "Google",    "affinity": "abstracted"},
    {"repo": "jax-ml/jax",                     "vendor": "Google",    "affinity": "abstracted"},
    {"repo": "pytorch/executorch",             "vendor": "Meta",      "affinity": "abstracted"},
    {"repo": "quic/aimet",                     "vendor": "Qualcomm",  "affinity": "native"},
    {"repo": "quic/ai-hub-models",             "vendor": "Qualcomm",  "affinity": "native"},
    {"repo": "quic/efficient-transformers",    "vendor": "Qualcomm",  "affinity": "native"},
]


def fetch_releases(repo: str) -> list[dict]:
    releases: list[dict] = []
    for page in range(1, MAX_RELEASES_PAGES + 1):
        try:
            r = requests.get(
                f"https://api.github.com/repos/{repo}/releases",
                params={"per_page": 100, "page": page},
                headers=HEADERS,
                timeout=20,
            )
            if r.status_code == 403:
                reset = r.headers.get("X-RateLimit-Reset")
                if reset:
                    wait = max(int(reset) - int(time.time()), 1)
                    print(f"    Rate limited, sleeping {wait}s")
                    time.sleep(wait + 1)
                    continue
                break
            if r.status_code != 200:
                print(f"    HTTP {r.status_code} for {repo} page {page}")
                break
            data = r.json()
            if not data:
                break
            releases.extend(data)
        except Exception as e:
            print(f"    ERROR {repo} page {page}: {e}")
            break
        time.sleep(REQUEST_DELAY)
    return releases


def main() -> int:
    print(f"\n=== GitHub Releases @ {datetime.now(timezone.utc).isoformat()} ===")
    print(f"Auth: {'token' if TOKEN else 'unauthenticated'}")
    print(f"Repos: {len(REPOS)}\n")

    rows: list[dict] = []
    for entry in REPOS:
        repo, vendor, affinity = entry["repo"], entry["vendor"], entry["affinity"]
        releases = fetch_releases(repo)
        total_dls = 0
        n_assets = 0
        for rel in releases:
            rel_tag = rel.get("tag_name", "")
            rel_name = rel.get("name", "")
            rel_published = rel.get("published_at")
            for asset in rel.get("assets", []) or []:
                dl = int(asset.get("download_count") or 0)
                rows.append({
                    "repo": repo,
                    "vendor": vendor,
                    "affinity": affinity,
                    "release_tag": rel_tag,
                    "release_name": rel_name,
                    "released_at": rel_published,
                    "asset_name": asset.get("name"),
                    "asset_size_bytes": int(asset.get("size") or 0),
                    "downloads": dl,
                    "fetched_at": datetime.now(timezone.utc),
                })
                total_dls += dl
                n_assets += 1
        print(f"  [{vendor:<10}] {repo:<40} {len(releases):>3} releases, "
              f"{n_assets:>4} assets, {total_dls:>10,} total downloads")
        time.sleep(REQUEST_DELAY)

    if not rows:
        print("\nNo release data collected.")
        return 1

    df = pd.DataFrame(rows)
    df["released_at"] = pd.to_datetime(df["released_at"], utc=True, errors="coerce")
    df.to_parquet(OUT_PATH, index=False)
    print(f"\n-> saved {len(df)} rows to {OUT_PATH}")

    # Summary by vendor
    print("\nBy vendor:")
    summary = df.groupby("vendor")["downloads"].sum().sort_values(ascending=False)
    for v, d in summary.items():
        print(f"  {v:<12} {d:>12,} cumulative downloads")
    return 0


if __name__ == "__main__":
    sys.exit(main())
